# -*- coding: utf-8 -*-
"""Financial_Analyst_RAG_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAUkTBlUo5FNglcTWpo0vCB690WrJ5TP
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/mritunjaypandey2k24/financial-analyst-rag.git
# %cd financial-analyst-rag

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

import torch
print(torch.cuda.is_available())  # Should return True

!ls

!pip install \
    sentence-transformers \
    faiss-cpu \
    numpy \
    transformers \
    beautifulsoup4 \
    pandas \
    PyPDF2

# Install the CUDA-specific version for Colab
!pip install faiss-gpu-cu12

from utils.retriever import DocumentRetriever
print("Retriever loaded successfully!")

from utils.data_fetcher import fetch_sec_filings

# Define companies and their CIKs
companies = {
    "Apple": "0000320193",
    "Microsoft": "0000789019"
}

# Fetch filings
for company, cik in companies.items():
    print(f"Fetching filings for {company}...")
    fetch_sec_filings(
        ticker=cik,
        filing_type="10-K",       # Annual reports
        save_directory=f"data/sec_filings/{company}",
        num_filings=3             # Number of filings to fetch
    )

from preprocessing import preprocess_file
import os

# Define company folders
company_folders = ["data/sec_filings/Apple", "data/sec_filings/Microsoft"]
processed_documents = {}

# Preprocess each company's filings
for folder in company_folders:
    print(f"Processing filings in {folder}...")
    documents = []
    for file_name in os.listdir(folder):
        try:
            file_path = os.path.join(folder, file_name)
            cleaned_text = preprocess_file(file_path)  # Unified preprocessing
            documents.append(cleaned_text)
        except Exception as e:
            print(f"Error processing {file_name}: {e}")
    processed_documents[folder] = documents

!pip install faiss-cpu

!nvidia-smi

import faiss
print("FAISS installed and ready to use!")

from utils.retriever import DocumentRetriever

indices = {}

for company, docs in processed_documents.items():
    # Initialize a retriever for each company
    retriever = DocumentRetriever()
    embeddings = retriever.create_embeddings(docs)
    retriever.build_index(embeddings)
    # Store the FAISS index
    indices[company] = retriever
    print(f"FAISS index built for {company}.")

!pip install sentence-transformers faiss-cpu numpy

torch.cuda.is_available()



from agent_pipeline import FinancialRAGAgent

rag_agent = FinancialRAGAgent()
question = "What was the total revenue in the last annual report?"

for company, retriever in indices.items():
    print(f"Querying {company}...")
    answer = rag_agent.answer_query(question, processed_documents[company])
    print(f"Answer for {company}: {answer}")

!git add notebooks/financial_analyst_rag.ipynb
!git commit -m "Updated RAG pipeline notebook"
!git push origin main

